apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mission-link
  name: mission-link-deployment
  labels:
    app: mission-link
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mission-link
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mission-link
    spec:
      containers:
        - image: 257840391579.dkr.ecr.ap-northeast-2.amazonaws.com/final:20230621084718
          imagePullPolicy: Always
          name: mission-link
          ports:
            - containerPort: 3000