apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 257840391579.dkr.ecr.ap-northeast-2.amazonaws.com/
  newName: 257840391579.dkr.ecr.ap-northeast-2.amazonaws.com/
  newTag: "20230622042107"
- name: 257840391579.dkr.ecr.ap-northeast-2.amazonaws.com/final
  newName: 257840391579.dkr.ecr.ap-northeast-2.amazonaws.com/final
  newTag: "20230621084718"
resources:
- ../../base
patches:
- path: deployment-patch.yaml
- path: service-patch.yaml
