apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 257840391579.dkr.ecr.ap-northeast-2.amazonaws.com/final
  newName: 257840391579.dkr.ecr.ap-northeast-2.amazonaws.com/final
  newTag: "20230623041137"
resources:
- ../../base
patches:
- path: deployment-patch.yaml
- path: service-patch.yaml
- target:
    kind: Ingress
    name: mission-link-ingress
  path: ingress-patch.yaml